# @package _global_
config:
  VERBOSE: False
  LOG_FREQUENCY: 100
  TEST_ONLY: False
  TEST_EVERY_NUM_EPOCH: 1
  TEST_MODEL: True
  SEED_VALUE: 1
  MULTI_PROCESSING_METHOD: forkserver
  HOOKS:
    PERF_STATS:
      MONITOR_PERF_STATS: True
      ROLLING_BTIME_FREQ: 313
      PERF_STAT_FREQUENCY: 10
    TENSORBOARD_SETUP:
      USE_TENSORBOARD: True
      FLUSH_EVERY_N_MIN: 20
  DATA:
    NUM_DATALOADER_WORKERS: 10
    TRAIN:
      BATCHSIZE_PER_REPLICA: 256
      TRANSFORMS:
        - name: RandomResizedCrop
          # size: 384
          size: 224
        - name: RandomHorizontalFlip
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
    TEST:
      BATCHSIZE_PER_REPLICA: 256
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 1
      topk_values: [1, 5]
  TRAINER:
    TRAIN_STEP_NAME: standard_train_step
  MODEL:
    FEATURE_EVAL_SETTINGS:
      EVAL_MODE_ON: True
      EVAL_TRUNK_AND_HEAD: False
    WEIGHTS_INIT:
      PARAMS_FILE: "specify model weights"
      STATE_DICT_KEY_NAME: "classy_state_dict"
      APPEND_PREFIX: "trunk."
    TRUNK:
      NAME: vision_transformer
      VISION_TRANSFORMERS:
        IMAGE_SIZE: 224
        PATCH_SIZE: 16
        NUM_LAYERS: 12
        NUM_HEADS: 3
        HIDDEN_DIM: 192
        MLP_DIM: 3072
        DROPOUT_RATE: 0.1
        ATTENTION_DROPOUT_RATE: 0
        CLASSIFIER: token
    HEAD:
      PARAMS: [
      ["mlp", {"dims": [192, 3072], "use_relu": True}],
      ["mlp", {"dims": [3072, 128]}],
      ]
    SYNC_BN_CONFIG:
      CONVERT_BN_TO_SYNC_BN: False
      SYNC_BN_TYPE: apex
      GROUP_SIZE: 4
    AMP_PARAMS:
      USE_AMP: True
      AMP_ARGS: {"opt_level": "O1"}
  LOSS:
    name: cross_entropy_multiple_output_single_target
    cross_entropy_multiple_output_single_target:
      ignore_index: -1
  OPTIMIZER:
    name: adamw
    weight_decay: 0.05
    num_epochs: 1000
    non_regularized_parameters: [pos_embedding, class_token]
    param_schedulers:
      lr:
        auto_lr_scaling:
          auto_scale: True
          base_value: 0.0005
          base_lr_batch_size: 1024
        name: composite
        schedulers:
          - name: linear
            start_value: 0.00001
            end_value: 0.0005
          - name: cosine
            start_value: 0.0005
            end_value: 0.000001
        interval_scaling: [rescaled, fixed]
        update_interval: epoch
        lengths: [0.05, 0.95]
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 4
    INIT_METHOD: tcp
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
  CHECKPOINT:
    DIR: "."
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 50
